Repository optimad/bitpit, pull requests merged in 2022-11, with the labels that each got.

#359 CG: fix in the triangulation of a polygon
  src/CG/CG_elem.cpp
Labels: bug, M - CG, P2 - Normal

#360 LA: optimize update of system matrix
  src/LA/system_solvers_large.cpp
Labels: enhancement, M - LA

#358 external/git: quote argument passed to function
  external/git/cmake/GetGitRevisionDescription.cmake
Labels: bug

#363 discretization: add some fast paths for constant polynomials
  src/discretization/reconstruction.cpp
  src/discretization/reconstruction.hpp
Labels: enhancement, M - discretization
