Repository optimad/bitpit, pull requests merged in 2023-06, with the labels that each got.

#397 examples: fixes for serial builds
  examples/RBF_example_00001.cpp
Labels: bug, M - RBF

#403 IO: do not require a space after the "solid" keyword of STL ASCII files
  src/IO/STL.cpp
Labels: enhancement, M - IO

#395 reconstruction: correct the computation of derivatives
  src/discretization/reconstruction.cpp
Labels: bug

#392 IO: fix writing of binary archive header
  src/IO/binary_archive.cpp
Labels: M - IO

#391 patchkernel: declare SkdNode constructors as public
  src/patchkernel/patch_skd_tree.cpp
  src/patchkernel/patch_skd_tree.hpp
Labels: M - patchkernel
